[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "XUfg1HSnzG2Yp9WV1j4fbMFUMujQetGKeG4XM1J3S3Z"

[programs.devnet]
counter = "XUfg1HSnzG2Yp9WV1j4fbMFUMujQetGKeG4XM1J3S3Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/yogesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
