[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_program = "7WDFmqyzVeCa34a6J4jyGTUPLmvsy6a3ZrHsRGG91V1m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/yogesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
